### ISSUE TITLE
little error

### ISSUE THREAD

**Issue by Santosian** [learn-co-curriculum/programming-univbasics-nds-hashes-of-hashes-lab#3]
This should be HoH instead of AoH

CREATING HoH

# AoH in one go
child = {:name=>"Carrie Fisher", :mother=>{:name=>"Debbie Reynolds", :mother=>{}, :father=>{}}, :father=>{:name=>"Eddie Fisher", :mother=>{}, :father=>{}}}
 
# Same as above, but using whitespace to make it easier for humans to read

**Comment by maxwellbenton** [comment]
Good catch! Thank you @Santosian. This has been fixed.
